language: node_js
node_js:
 - "iojs"

sudo: required
os: linux
dist: trusty

service: docker
env:
 - DOCKER_COMPOSE_VERSION=2.0
 
before_install:
 - sudo apt update
 - sudo apt-get install docker-ce

install: sudo docker-compose up --build &

before_script:
 - cd src/server
 - npm install mocha
 
script:
 - npm test
