language: node_js
node_js:
 - lts/*

sudo: required
os: linux
dist: trusty

service: docker

addons:
 firefox : latest
 apt:
  package: docker-ce
 sonarcloud:
  organization: francoisaudoy-github
 
before_install:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sleep 3
 - stty cols 80

install:
 - sudo docker-compose build
 - sudo docker-compose up -d
 
script:
 - sonar-scanner -Dsonar.login=${SONAR_LOGIN}
 - cd src/server
 - npm install mocha supertest should 
 - npm test
 - cd ../cdp_24_app/
 - npm install
 - npm test

notifications:
 email: false