language: node_js
node_js:
 - "iojs"
sudo: required

before_install: sudo apt-get install docker-compose

install: sudo docker-compose up --build

before_script:
 - cd src/server
 - npm install -g mocha

script:
 - npm test
