language: node_js
node_js:
 - lts/*

sudo: required
os: linux
dist: trusty

service: docker

addons:
 firefox : latest
 
before_install:
 - sudo apt update
 - sudo apt-get install docker-ce
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sleep 3
 - stty cols 80

install:
 - sudo docker-compose build
 - sudo docker-compose up -d

before_script:
 - cd src/server
 - npm install mocha supertest should testcafe 
 
script:
- npm test

notifications:
 email: false