language: node_js
node_js:
 - lts/*

sudo: required
os: linux
dist: trusty

service: docker

addons:
 firefox : latest
 
before_install:
 - sudo apt update
 - sudo apt-get install docker-ce

install:
 - sudo docker-compose build
 - sudo docker-compose up

before_script:
 - cd src/server
 - npm install mocha supertest should testcafe 
 
script:
- npm test

notifications:
 email: false